# Generated by Django 4.1.2 on 2022-11-10 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avanzado', '0003_rename_fecha_nacimiento_mascota_fecha_de_creacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='edad',
            new_name='edad_media_de_vida',
        ),
    ]
