# Generated by Django 4.1.2 on 2022-11-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avanzado', '0005_mascota_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='avatar',
        ),
        migrations.AddField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
